version: '3'
services: 
  banco:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: cami
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: devops
  api:
    build: 
      context: ./api
    environment:
      API_PORT : 3000
      API_DB: "postgres://cami:devops123@banco/devops"
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    environment:
      WEB_PORT: 3000
      API_HOST: http://api:3000
